/**
 * Captions for the full archive (everything outside the curated
 * PREVIEW_CAPTIONS set in photos.ts). Written by looking at each actual
 * photo — grounded in what's visible, nothing invented about the
 * relationship itself. Short, lowercase, place/moment-observational, same
 * register as the curated set.
 */
export const ARCHIVE_CAPTIONS: Record<string, { caption: string; alt: string; mood?: string }> = {
  "photo-004": { caption: "lunch on the terrace", alt: "wrapped in an orange blanket, pasta and a cocktail" },
  "photo-006": { caption: "down a side street", alt: "standing in a narrow lane, drink cans in hand" },
  "photo-008": { caption: "sunglasses by the harbour", alt: "standing at a harbour wall, sea and town behind" },
  "photo-011": { caption: "moonlit on the dock", alt: "sitting together on a jetty, moon over the water", mood: "late-night" },
  "photo-012": { caption: "goofing around in bed", alt: "a couple in bed, one pulling a face", mood: "laughing" },
  "photo-014": { caption: "flowers in her hair", alt: "standing in a field, flowers tucked into her hair", mood: "golden" },
  "photo-015": { caption: "the view from the tent", alt: "looking out of a tent over a grassy clifftop" },
  "photo-017": { caption: "smiling for a selfie", alt: "a selfie together, a brick wall behind" },
  "photo-018": { caption: "a kiss in the lift", alt: "a forehead kiss caught in a mirrored lift", mood: "gentle" },
  "photo-019": { caption: "dinner, caught smiling", alt: "seated at a restaurant table, lamp glowing beside her", mood: "soft" },
  "photo-020": { caption: "caught looking away", alt: "candid, in profile at the dinner table" },
  "photo-022": { caption: "a pint and some work", alt: "a laptop and a pint on a pub table" },
  "photo-023": { caption: "curled up together", alt: "a couple close together on the sofa, laptop nearby", mood: "home" },
  "photo-024": { caption: "a video call screenshot", alt: "a video call on screen beside a dissertation document" },
  "photo-025": { caption: "resting on the sofa", alt: "a couple close together, laptop screen open beside them", mood: "home" },
  "photo-026": { caption: "a silhouette at the window", alt: "a figure silhouetted against a lit city skyline", mood: "late-night" },
  "photo-027": { caption: "an extreme close up", alt: "a close up selfie, finger resting near the chin" },
  "photo-028": { caption: "cricket and a pint", alt: "cricket on a laptop next to a pint" },
  "photo-029": { caption: "on the bus", alt: "smiling on a bus, the street passing by outside" },
  "photo-030": { caption: "cheek to cheek", alt: "a close up selfie, cheek to cheek" },
  "photo-031": { caption: "a toast at sunset", alt: "a couple in the water, drinks raised at sunset", mood: "golden" },
  "photo-032": { caption: "a family photo", alt: "two adults and a child posing by the water" },
  "photo-033": { caption: "by the river", alt: "a couple embracing beside a rocky stream" },
  "photo-034": { caption: "taking in the view", alt: "a couple with their backs to camera, mountains ahead" },
  "photo-035": { caption: "a hug from behind", alt: "a man wrapping his arms around a seated woman", mood: "laughing" },
  "photo-036": { caption: "a silly selfie", alt: "a couple close up, one flashing a shaka sign", mood: "laughing" },
  "photo-037": { caption: "the balcony at night", alt: "a couple on a balcony, harbour lights behind", mood: "late-night" },
  "photo-038": { caption: "up through the fog", alt: "feet dangling from a lift, fog covering the mountainside" },
  "photo-039": { caption: "at the gate", alt: "standing on the tarmac, backpack on, plane behind" },
  "photo-040": { caption: "sunset by the lake", alt: "by a lake at sunset, wrapped in a shawl", mood: "golden" },
  "photo-041": { caption: "sunset by the lake", alt: "a couple embracing by a still lake at sunset, hills reflected in the water", mood: "golden" },
  "photo-042": { caption: "a horse by the coast", alt: "standing beside a large black horse on a grassy clifftop above a beach", mood: "golden" },
  "photo-043": { caption: "by the harbour railings", alt: "a man pointing towards the camera by railings, a lake and mountains behind" },
  "photo-044": { caption: "on the balcony", alt: "standing on a balcony overlooking a green hillside and a garden terrace" },
  "photo-045": { caption: "a childhood costume photo", alt: "a young girl in a blue folk costume standing against a wall" },
  "photo-046": { caption: "selfie in the clouds", alt: "a selfie on a misty hillside, one making a peace sign" },
  "photo-047": { caption: "hands on the console", alt: "a view from the back seat of a car, hands joined on the centre console" },
  "photo-048": { caption: "night above the harbour", alt: "a couple standing on a rooftop terrace above a harbour lit up at night", mood: "late-night" },
  "photo-049": { caption: "meeting a foal", alt: "crouching beside a small white foal in a grassy field with yellow gorse" },
  "photo-050": { caption: "the balcony at night", alt: "standing at a balcony railing above a city lit up at night", mood: "late-night" },
  "photo-051": { caption: "a kiss in the lift", alt: "a kiss caught in a mirror selfie inside a lift", mood: "gentle" },
  "photo-052": { caption: "a childhood teddy bear", alt: "a man and a young girl holding a large teddy bear", mood: "home" },
  "photo-053": { caption: "the retro seaside cafe", alt: "walking through a cafe lined with vintage radios, the sea beyond" },
  "photo-054": { caption: "dusk over the bay", alt: "resting by a window with a lit up bay visible at dusk", mood: "soft" },
  "photo-055": { caption: "a childhood birthday photo", alt: "a young girl standing under a happy birthday banner" },
  "photo-056": { caption: "a close, backlit portrait", alt: "a close up portrait with sunlit hair against a dark background", mood: "golden" },
  "photo-057": { caption: "getting ready, a mirror selfie", alt: "a mirror selfie in a floral dress, a kitchen visible through the doorway" },
  "photo-058": { caption: "the hot tub view", alt: "a couple in a rooftop hot tub overlooking the sea" },
  "photo-059": { caption: "driving through the mountains", alt: "a view from the back seat of a car driving past mountains, sunroof open" },
  "photo-060": { caption: "vintage radios and a globe", alt: "an old radio and globe on a cabinet, jazz clippings papering the wall" },
  "photo-061": { caption: "the mountain road", alt: "a view from the back seat of a car with a mountain through the sunroof" },
  "photo-062": { caption: "the retro corner", alt: "a corner of vintage radios, a globe and jazz clippings on the wall" },
  "photo-063": { caption: "swept off her feet", alt: "a man carrying a woman by the water, mountains behind", mood: "laughing" },
  "photo-064": { caption: "an old family selfie", alt: "a young girl and a man taking a selfie under a thatched roof" },
  "photo-065": { caption: "together on the balcony", alt: "a couple close together on a balcony at night, a harbour lit up below", mood: "late-night" },
  "photo-066": { caption: "an embrace on the beach", alt: "a couple embracing on a beach lined with sun loungers and palm trees", mood: "gentle" },
  "photo-067": { caption: "the lake at sunset", alt: "standing by a still lake at sunset, hills reflected in the water", mood: "golden" },
  "photo-068": { caption: "a mirror selfie together", alt: "a couple in a mirror selfie, one wearing a sun hat" },
  "photo-069": { caption: "the ship cabin", alt: "standing in a small cabin with a bunk bed and wood panelling" },
  "photo-070": { caption: "the skyline at dusk", alt: "standing on a hill with a city skyline lit up at dusk", mood: "soft" },
  "photo-071": { caption: "the road ahead", alt: "a passenger seat view of a road between green hedges" },
  "photo-072": { caption: "a night out", alt: "smiling on a city street at night, black cabs passing" },
  "photo-073": { caption: "arrows in the target", alt: "several arrows stuck in an indoor archery target" },
  "photo-074": { caption: "this is a pipe", alt: "pointing at a framed painting that reads this is a pipe" },
  "photo-075": { caption: "a boat trip", alt: "a selfie on a boat together, riverside towers behind" },
  "photo-076": { caption: "get naked", alt: "standing on a bath mat that reads get naked" },
  "photo-077": { caption: "pointing at the target", alt: "a selfie at the archery range, arrows in the bullseye" },
  "photo-078": { caption: "on the train", alt: "laughing behind her hand on a train, headscarf on" },
  "photo-079": { caption: "grocery run", alt: "a lift mirror selfie, arms full of shopping" },
  "photo-080": { caption: "arms up at the rink", alt: "arms raised on an outdoor ice rink, christmas tree behind" },
  "photo-081": { caption: "churros and chocolate", alt: "eating churros with chocolate dip at a lit up market" },
  "photo-082": { caption: "past the london eye", alt: "a boat selfie together, the london eye glowing behind" },
  "photo-083": { caption: "the kitchen floor spill", alt: "curled up on the kitchen floor next to a spill" },
  "photo-084": { caption: "on the train again", alt: "seated on a train in a headscarf, looking at the camera" },
  "photo-085": { caption: "a kiss over dinner", alt: "a kiss on the head, mezze spread across the table", mood: "gentle" },
  "photo-086": { caption: "moving in", alt: "standing in a bare dorm room with a backpack on" },
  "photo-087": { caption: "up too close", alt: "an extreme close up selfie, faces squished together" },
  "photo-088": { caption: "golden hour in the field", alt: "a selfie in a golden field at sunset, town in the distance", mood: "golden" },
  "photo-089": { caption: "hot chocolate by the sea", alt: "sipping hot chocolate at a table overlooking the beach", mood: "soft" },
  "photo-090": { caption: "sunglasses and sunshine", alt: "a sunny day selfie, adjusting round sunglasses" },
  "photo-091": { caption: "rolling out dough", alt: "grinning in the kitchen with a rolling pin and flour", mood: "home" },
  "photo-092": { caption: "canary wharf at dusk", alt: "looking out over a skyline from a grassy hill at dusk", mood: "soft" },
  "photo-093": { caption: "adjusting an earring", alt: "standing by the window on a night boat, skyline behind", mood: "late-night" },
  "photo-094": { caption: "the new tattoo", alt: "a close up of a small tattoo on his back" },
  "photo-095": { caption: "dinner is ready", alt: "flatbread and bowls of soup set out on the table", mood: "home" },
  "photo-096": { caption: "holding hands in the car", alt: "two hands clasped together on a car console", mood: "gentle" },
  "photo-097": { caption: "in red and gold", alt: "standing outside in a red and gold saree, palm trees lit up behind" },
  "photo-098": { caption: "caught laughing", alt: "laughing on a night cruise, drink in hand, skyline behind", mood: "laughing" },
  "photo-099": { caption: "mountains across the water", alt: "a couple standing by a railing, steep green mountains across the water" },
  "photo-100": { caption: "sunset by the lake", alt: "an embrace by a lake at sunset, hills reflected in the water", mood: "golden" },
};
